### ISSUE TITLE
Amazing quality. Should be at some point a part of a core IMHO

### ISSUE THREAD

**Issue by riabiy-denis** [michael-rubel/laravel-enhanced-pipeline#12]
Really, just thank you for your work. You've even used the right Contract, so I'm not afraid to rely on this package. Worst-case -> could be swapped/vendor-sourced. 

Just thank you for making a package out of it. ❤️

**Comment by riabiy-denis** [comment]
Feel free to ~burn~ close after reading.

**Comment by michael-rubel** [comment]
@riabiy-denis Thank you for your kind words!
The fact that someone liked my work so much proves that my time invested in open-sourcing wasn't wasted entirely. 😉

**Comment by riabiy-denis** [comment]
100%
