### ISSUE TITLE
question about transactions

### ISSUE THREAD

**Issue by michabbb** [michael-rubel/laravel-enhanced-pipeline#8]
hi there.
thanks for this package!
i guess i don´t understand the logic where the final transaction-commit happens, that´s why I want to ask.
the code looks to me like there happens a transaction inside each element of the pipe and at the final end of all
jobs inside the pipe. am I wrong here? thanks!

https://github.com/michael-rubel/laravel-enhanced-pipeline/blob/a2f1c7e4b173d8414f0f74a267c9b999d0d190d6/src/Pipeline.php#L262

**Comment by michael-rubel** [comment]
Hi @michabbb 

The transaction commits once, at the end of the entire pipeline.
If the pipeline fails, it makes the transaction rollback:
https://github.com/michael-rubel/laravel-enhanced-pipeline/blob/a2f1c7e4b173d8414f0f74a267c9b999d0d190d6/src/Pipeline.php#L153

If you want transactions only of some pipes of the pipeline, it's better to control the transactions manually and not to use `withTransaction()`.

**Comment by michabbb** [comment]
thanks for the clarification. i am not so familiar with pipes but your package encourages me more to think about using that, but I was confused because your "commit" is inside your "try....catch", that´s why I was confused. thanks.
